### ISSUE TITLE
Add more characters to punctuations

### ISSUE THREAD

**Issue by GrimPixel** [dessalines/thumb-key#104]
Characters to be added:
* quotation marks and guillemets “”„‘’‚«»‹›
* dashes –—
* inverse question and exclamation marks ¿¡
* currency symbols ฿₿₵¢₡₫֏Ξƒ₲₴₭₾₺₼₦₱£﷼៛₽ރ₹₪৳₸₮₩¥¤

**Comment by dessalines** [comment]
Not enough space on the numeric keyboard for all of those. Definitely not going to add things like curly quotes either.

**Comment by GrimPixel** [comment]
The currency symbols are fewer than emoji. They are all common for their users, as they are all circulating.

**Comment by LongJohn-Silver** [comment]
IMO currency should be something that can be set up in the settings menu along with the language of the keyboard, so that your primary currency matches  the former, but also showing the "international" currencies (Dollar, Euro, etc).

While I agree making it too clutter is not a good idea, I think expanding it a little bit would be useful, for example having two pages, one with the more used ones and the other with the lesser used but still somewhat needed. This is what Florisboard does.

First category, numbers are included in this one:
 - + ´ ! / ? ( % _ ) @ : " , *  . - ' # ; & º 

Second category:
~ ` |$ € ^   = { } \ _ © ® ™ ✓[ ]

These are missing from the second category
· √  π ÷ × (Not the same as ´x´ or ´X´) ¶ Δ £ ¢ (Cent sign, for some reason GitHub doesn't display it correctly) 

Also the - symbol is repeated, it appears once in the number 1 and again in the number 8.

----

Also, while this should be its own issue, do you think there could be a chance of adding a row specifically for numbers? I think there's not need to make them slide for other options or such thing, but I like having them up there even if it takes a little more screen space.

**Comment by dessalines** [comment]
No, I don't want to add a numbers row. Click the numeric keyboard.

**Comment by GrimPixel** [comment]
> No, I don't want to add a numbers row. Click the numeric keyboard.

Could you say “because it would be higher in position and harder to reach”, instead of “I don't want”? Everyone has their own thoughts and it is the reasoning that matters.

**Comment by breversa** [comment]
In addition, is it possible to display the characters (in muted color?) on the spacebar so that users *know* they are here to begin with ? :)

**Comment by dessalines** [comment]
I'd rather not clutter it up with indicators. The readme / guide should have all of those "special features".

**Comment by CGenie** [comment]
I would add some symbols to the basic, lower-case letter layout: comma, question and exclamation marks, colon and semicolon (used for emojis).

**Comment by CGenie** [comment]
Also "double space = a dot" is quite useful.

**Comment by pshirshov** [comment]
MessageEase has an option to add punctuations into primary view (the also may be invisible but still would work).

It would be nice to have something like that in thumbkey.

**Comment by dessalines** [comment]
Check the thumbkey programmers layout.

**Comment by pshirshov** [comment]
Can't find it there. But I would definitely prefer anihortes layout after 14 years of using it with messageease and being able to type about 300 cpm on it.

**Comment by pshirshov** [comment]
Ah, actually there is "messagease with symbols" layout in the latest version.

That's awesome.

It would be nice though if we can have replicas of messagease layouts for other languages too.

**Comment by dessalines** [comment]
Feel free to add them, there are instructions on adding layouts on the readme.

**Comment by spacemessenger** [comment]
Just hopping in this thread to say we should at least be able to choose our primary currency symbols in the settings to replace the € and £. I'm in the U.S. so neither of those are useful to me.

**Comment by dessalines** [comment]
The $ already exists on the numeric keyboard. You can create a custom numeric layout to remove those if you want, but I've tried to keep the numeric layout as universal as possible, as it is used by most layouts, and it seems redundant to create language or regional-specific numeric layouts.

**Comment by spacemessenger** [comment]
Ah, my apologies. I got the app last night and saw the other currency symbols and assumed they would all be in the same square.

**Comment by dessalines** [comment]
No probs. I'll close this issue as its vague, but will be open to PRs adding specific useful characters to the numeric layout.

**Comment by yurikhan** [comment]
> Definitely not going to add things like curly quotes either.

Does that mean any PR to add those to an existing or new layout will be rejected? I see some free spots in ThumbKeyENv4Symbols and typographic punctuation is a deal breaker for me.

MessageEase may be unmaintained but it supports them, by using the swipe-and-return gesture in addition to simple swipes.

**Comment by dessalines** [comment]
Again, I'll add any layout people ask for. I recommend working with the existing ones.
