### ISSUE TITLE
Upgrade the default numpad to mimic/be the t9 layout

### ISSUE THREAD

**Issue by EmersonBiggons** [dessalines/thumb-key#1088]
### Language

English

### Variant

(all layouts), with t9 numbpad

### Kind of request

Changes on an existing layout

### To keep it consise I'm going to write a few varients. I have zero coding knowledge so grain of salt.

- **Varient 1 Idea:** Simply Copypasta the T9 layout and replace the numbpad with it. Straight 1:1 copy. 

- **Varient 2 Idea:** Edit the symbols in the numbpad to mimic/approximate the T9 layout.

- **Varient 3 Idea:** mix of varient 1 and default with the option to switch between. (preferably this as I use all of the T9 layout funcionality: eg, spreadsheets. But I understand others do not.)

- **Varient 4 Idea:** Add the ability to edit individual buttons manually without having to request a new layout; A layout creator/editor. (Sorry if this already exists I just didn't find it)

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by EmersonBiggons** [comment]
Hopefully, I formatted this adequately.

**Comment by EmersonBiggons** [comment]
Missinput

**Comment by dessalines** [comment]
Currently numeric layouts are attached to specific keyboard layouts (which makes sense, because different countries / languages have different numeric systems). We don't have a way to set a custom numeric keypad, that would apply to any layout.

I'm not going to work on this because I think the current way is probably best, but I'll re-open if someone wants to make the numeric layout customizeable. It would entail:

- Removing all the numeric layouts from keyboard definitions
- Creating a DB setting for a numeric layout, similar to keyboard layouts, and a switcher that lets you choose them.

**Comment by EmersonBiggons** [comment]
Fair enough, hopefully this is sort of possible in the future, or someone picks up the project for it. Thank you for your time!
