### ISSUE TITLE
Reset multitaps when other key is pressed

### ISSUE THREAD

**Issue by dessalines** [dessalines/thumb-key#143]

**Comment by terrylaire** [comment]
Hi! Thank you for the keyboard, it's fun to learn! I screenshot a problem I saw on Android v0.0.14 (sorry I'm not on 1.0.0, F-Droid is always late to the party) to create an issue, but this one looks similar so I'm adding the screenshots here to show some cases. All this is done with multitap activated, and of course is not a problem with multitap deactivated.

When you use the UI of an app (Whatsapp here) to add an emoji after a space and the proceed to add another space, multitap takes the lead and kills the emoji (at least a part of it, since I guess emojis are encoded on multiple bytes... sometimes deleting one byte changes the emoji!)
![Screenshot_20230507_010010_1](https://user-images.githubusercontent.com/49682169/236649835-2aa316f6-9ea3-4fcb-936b-e89b255d4215.jpg)
![Screenshot_20230507_010017_1](https://user-images.githubusercontent.com/49682169/236649836-085d2447-d79f-4a21-9d91-fcbb582b0f68.jpg)

The keyboard has the same problem when you enter a space, and then tap somewhere else on your text and add another space : the keyboard thinks it's multitap and deletes a part of the existing text
![Screenshot_20230507_010146_1](https://user-images.githubusercontent.com/49682169/236649838-daa3ea17-506c-42e0-90d5-17226c8399ff.jpg)
![Screenshot_20230507_010157_1](https://user-images.githubusercontent.com/49682169/236649840-a150ab25-a0a6-45ac-b1e9-c3988be77543.jpg)

And another way to do it is to enter a space, paste something (not with the keyboard, but by tapping the cursor and selecting the Android contextual menu "paste") and add another space after the text pasted. A part of the pasted text is deleted by multitap.
![Screenshot_20230507_010554_1](https://user-images.githubusercontent.com/49682169/236649841-89f34ead-cd09-43c5-81a9-59a6958b0f3d.jpg)
![Screenshot_20230507_010601_1](https://user-images.githubusercontent.com/49682169/236649842-56585d9d-a702-42e3-ac51-f4cd4934ca89.jpg)

Hope you can fix it without a headache!

**Comment by terrylaire** [comment]
Thank you for the izzyondroid tip! I confirm the behavior still exists in v1.0.0

**Comment by dessalines** [comment]
I can't seem to replicate this, for all the cases above. Can anyone else get this behavior?
