### ISSUE TITLE
bi- and trigrams

### ISSUE THREAD

**Issue by erik55** [dessalines/thumb-key#150]
Did you take bigrams and trigrams into consideration for the positions of the letters? Seems not. I did not know messagease before. Tried it out. Was surprised how much better balanced the positions of the letters felt already in the first moment of trying. Also I used both thumbs much more evenly, as messagease seems to be optimized for common bigrams. 

You criteria which I read somewhere is only vocals on one side, consonants on the other side. But that makes it really slow. 

I stopped using thumb key for now, as this makes typing really slow and inefficient (repetitive use of one finger over and over in zig zag directions, not in one flow which is something I experienced in the first few minutes of using messagease). 

I switched back to Multiling o which unfortunately also seems to be unmaintained now – and not open sourced. But it is perfect if you write in many languages every day, like me. I can easily switch them, and the prediction adapts to the new language. Prediction is not necessary for thumb key and messagease, which is great. But I am also typing blind on Multiling o just watching the text field. So that is not only possible with messagease and thumb key. 

I still find thumb key very interesting, but as long as the letters are distributed in an inefficient QWERTY way, it seems unusable to me. Can't understand how other users didn't mention or notice that before. 

As I already wrote: I write many languages every day. Mostly European. But I need diacritics. I saw that messagease allows to modify a letter by sliding into a corner, which gives you different variants of diacritics for a letter. That is also completely missing in thumb key. Therefore thumb key seems to be useful only for people that always write in only exactly one language.

**Comment by dessalines** [comment]
> Did you take bigrams and trigrams into consideration for the positions of the letters? Seems not. I did not know messagease before. Tried it out. Was surprised how much better balanced the positions of the letters felt already in the first moment of trying. Also I used both thumbs much more evenly, as messagease seems to be optimized for common bigrams.

MessageEase is definitely **not** optimized for bigrams / trigrams. If you read their key placement methodology, after the first 9 letters, they place letters based on whether or not they're *curve shaped*, completely ignoring any bigram or alternating thumb optimization. One of the most common bigrams / trigrams, `th` / `tha`, is typed entirely with the left thumb.

They also don't optimize for alternating thumbs, whereas I chose that as primary. You can go through this list of [bigrams / trigrams](https://mathcenter.oxford.emory.edu/site/math125/englishLetterFreqs/) to see for yourself how much worse messageease is in that regard.

The only thing that could better the design, is using an AI / evolutionary algorithm approach to the problem, using letter frequency and alternating thumbs, rather than doing manual key picking. I welcome anyone to do that

> But it is perfect if you write in many languages every day, like me. I can easily switch them, and the prediction adapts to the new language.

Thumb-key already has this. Go to your settings, select multiple languages, then use the swipe left on the number key to toggle between them quickly.

Also, use https://lemmy.ml/c/thumbkey for discussion-related items.
