### ISSUE TITLE
slovak layout

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#151]
please add a layout for typing in Slovak. thank you.
possibly, once i get better at typing in this keyboard,i could even pr the layout (maybe).

**Comment by dessalines** [comment]
https://github.com/dessalines/thumb-key#how-do-i-add-my-language-or-layout

**Comment by KraXen72** [comment]
i will pr this later

**Comment by dessalines** [comment]
Then don't close the issue. In your commit message, put `Fixes #X` issue, then this will close automatically.

**Comment by DJsushi** [comment]
I am currently working on this as well. I did some research on the Slovak dictionary from [here](https://korpus.sk/korpusy-a-databazy/databazy/morfologicka-databaza/) and found out these statistics:

Word count: 1177279
Average word length: 10.478342856706014
Longest word: najchminianskojakubovianskejšieho
Shortest word: A
Letter counts: {e=1155883, o=1012375, a=981375, n=884198, i=774631, r=590074, v=544499, t=524154, k=508491, m=482282, l=443927, s=420894, j=399341, u=387812, p=336897, d=307857, c=304274, h=268619, z=251135, š=243745, á=223919, b=171371, í=165426, č=143631, y=124159, ú=123057, ý=94648, é=70369, g=67015, f=61173, ž=60779, ť=59325, ľ=57014, ň=22819, ó=18237, x=10383, ô=7181, ď=6941, ä=6907, ŕ=5909, ĺ=3017, A=988, w=932, M=709, B=627, S=568, D=473, K=463, V=449, P=449, R=416, T=351, J=329, E=298, L=293, I=262, H=254, N=224, O=221, Z=209, G=199, F=191, ö=187, C=151, Š=126, q=102, Ľ=100, U=96, *=79, Ž=73, Č=72, ř=49, ě=49, ü=36, W=34, Á=23, è=22, Ú=21, X=19, Y=10, Ď=8, å=8, Í=4, 1=4, ê=3, Q=3, 2=1, à=1, '=1, Ť=1, 3=1, Ö=1}

These letter counts are a little biased because the Slovak morphological database contains all the words including their inflections. That means, that if we have for example the word 'najchminianskojakubovianskejšieho', it's inside the database multiple times inflected to its correct form, driving some letter statistics artificially up and down. But it should be good enough.

**Comment by KraXen72** [comment]
very nice, thanks. personally, im not that interested in making a slovak-first layout for myself, i'd just make a layout which is based on en-v4 and has slovak accented characters, because i already am used to the letter positions of env4 and i mostly type in english anyways, or it's not worth it for me to learn a different layout just to type in slovak.

however, i am aware that in the long run, for people who type primarily in slovak, a slovak-centric layout would definitely be better.

tangentally related, but this is what i've come up so far for the en-sk multilayout:
![slovak keyboard](https://github.com/dessalines/thumb-key/assets/21956756/7ef6a5af-e64e-4c9c-891b-7667a132cfd4)

feel free to drop suggestions, i guess. i still got other things i've gotta do anyway, so i don't know yet when i'll get to this.

**Comment by dessalines** [comment]
Thanks for finding that info @DJsushi , I wouldn't wait on kraxen to make an anglo-slovak layout., you could continue making a slovak layout using those letter frequencies.

**Comment by dessalines** [comment]
I'll reopen this if someone should decide to add one.

**Comment by tothpsk** [comment]
Hi all, thank you for your work concerning Slovak keyboard layout. I was using it for a week now but I have to say it does not suit me. That layout is based on English letters frequency, but Slovak language has different letter preferences (A O E S N I T R V L K D M C U P Z Y H J G F B (Q W X) (Mistrik 1985)). Following the instructions by @dessalines I created a more suitable layout which respects Slovak language specifics:
![image](https://github.com/dessalines/thumb-key/assets/11166910/109f9587-2d77-4115-8949-2fd6e1e4ace4)

I am uploading the keyboard layout if you would like to test it: [SKThumbKey.zip](https://github.com/dessalines/thumb-key/files/15075542/SKThumbKey.zip)

**Comment by dessalines** [comment]
Sweet thx! I'll add this shortly as an alternate slovak layout.
