### ISSUE TITLE
Mirror the Shift/caps functionality on the left side of the keyboard as well.

### ISSUE THREAD

**Issue by src52** [dessalines/thumb-key#156]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **

In typical PC keyboard use, there are two Shift keys on either side of the keyboard. The Shift key opposite to the key being shifted is used to avoid uncomfortable finger stretching (using the same hand to press Shift + another key), and to force the user to use two hands (one for Shift, one for another key).

A similar argument can be made for this keyboard. It is a bit awkward and slower to activate Shift, then press A, or L, for example. 

This can be alleviated by mirroring the Shift/caps functionality on the left side of the keyboard as well. That way one hand's finger can be used to Shift, while the opposite hand types the shifted key. 

Thoughts?

**Comment by dessalines** [comment]
Having the shift key meet the same alternating thumb requirements as the other keys, seems way overkill. It isn't a very common key, and if auto-shift is working correctly, you should rarely have to activate it.

Physical keyboards also require you to hold down keys, which is why you see duplicated keys like shift, control, and alt, on both sides of the keyboard.

If you want to design a special english keyboard that has two shifts, I'd be glad to merge it, but this seems way overkill.
