### ISSUE TITLE
text-expansion shortcuts

### ISSUE THREAD

**Issue by KraXen72** [dessalines/thumb-key#162]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.

** Describe the feature request below **
text shortcuts - you could set up some longer text to be suggested/replaced after typing a shortcut. it could be useful when typing 1 thing a lot, for example your e-mail.

**Comment by dessalines** [comment]
I could see this being useful for sure. Its def in the far future for me tho, unless anyone else wants to work on it.

**Comment by racuna** [comment]
I'm using Text Tools for now. Mostly for autofill stuff like emails, addresses, and common phrases in messaging apps. 

https://github.com/lochidev/TextToolsPro

**Comment by dessalines** [comment]
Nice. Yeah this is probably better suited to an app made for that purpose.

**Comment by quasipedia** [comment]
While I have no issue with the developer wanting to focus their efforts elsewhere (in fact: thank you for the app in the first place! 🙏), given the focus of thumb-key on privacy I woud disagree with the rationale that this is better suited for a dedicated app.

A text expansion app will have to access every keystroke typed, de-facto doubling the attack surface.

I see macros as input expansion (rather than text transformations).

Again: all the same if this isn't planned anyway... but it would be sad if somebody would make a PR and the dev would decline to merge on the ground of "better suited elsewhere"... 🙂

**Comment by dessalines** [comment]
TextToolsPro is fully open source, and is going to be much better featured than anything we could build here. Not only that, but it works for **all keyboards**

Why duplicate efforts? Anyone building more macro functionality should do it there, not here.

**Comment by quasipedia** [comment]
I would follow the same approach for a system without security implication (as you say: why duplicating effort?  and I would add: why losing focus?). Being orthogonal is a good architectural principle IMO.

For a secure system though, I would typically avoid external dependencies to keep the attack surface to a minimum. This - incidentally - is why banks tend to reimplement in-house the functionality provided by open libraries (because they want to be sure no malicious code is pulled in), or why VPN providers offer DNS and ad blockers with their offering (not to expose the traffic - even if anonymised - to third parties who may or may not be honest or competent).

In this specific case also: have you noticed that the author is essentially saying that the software is not any more actively developed?  They will only look at it now-and-then. :disappointed: 

Anyway: this (trying to convince you that macros belong to an input system) is not the hill I'm going to die on! :smile: 

It's a feature that I can leave without.  Rather, again: thank you for maintaining this project, I really appreciate it! :raised_hands: :raised_hands: :raised_hands:
