### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by pxeemo** [dessalines/thumb-key#196]
**Thumb-Key Version**

Version 0.0.13

**Describe the bug**

Some of languages enable RTL layout direction mode.
Everything mirrors correctly but swipings are still the same as LTR layout. All right/left swipings must be start/end (up and down is correct).

![IMG_20230502_165348](https://user-images.githubusercontent.com/67392584/235684065-dceb77ed-fa5e-4656-a3f7-f10768b53112.jpg)

**To Reproduce**

1. Open mobile settings.
2. Go to Developer options.
3. Scroll down to Drawing.
4. Click on Force RTL layout direction toggle.
5. Reopen the Thumb-key.
6. Swipe to right/left to type a character.

It's also observable by changing to an RTL language like Arabic.

**Comment by mpice-mn** [comment]
I've found a rather [simple fix](https://github.com/mpice-mn/thumb-key/commit/7a5fb997d1f751bd35e78d03bdc52b5fc6dbac65) for this (inverting offsetX when RTL mode is on). This fixes the swipe gestures when I force RTL via the dev options on my device. Some punctuation characters still behave strange, but maybe that just because I'm testing with a LTR language in RTL mode.

I'm not an RTL user myself, so here's a [test apk](https://github.com/mpice-mn/thumb-key/releases/tag/v1.0.0-rtl.1) in case somebody (@pexemo?) wants to give it a try.

**Comment by pexemo** [comment]
I don't use RTL either, but in my test it everything works fine except the spacebar. It should be the same as LTR.

**Comment by dessalines** [comment]
I'll re-open if anyone wants to take this on.

**Comment by pxeemo** [comment]
Hi! I was thinking about this issue recently. I realized that normal keyboard layouts don't follow the system's layout direction. 
Since the app already supports RTL in settings, I thought it would be better to keep the keyboard layout always in LTR to fix this issue. 
If you agree, I'd be happy to add a pull request for this.

**Comment by dessalines** [comment]
Sure, although it'd be best if we had someone who uses an rtl language to test and make sure it's working correctly.

**Comment by pxeemo** [comment]
I already use an RTL language, but I don't have it set as the systemwide language. However, I can test how it works. Also, I built a test APK for my friend, and it worked fine there.

**Comment by dessalines** [comment]
Sweet, thx!
