### ISSUE TITLE
Voice input button

### ISSUE THREAD

**Issue by dmackca** [dessalines/thumb-key#210]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

Similar to Gboard (and other keyboards?), it would be nice to have a button to toggle the microphone input for accessibility/convenience. I'm sure it would complicate things as far as privacy goes, but maybe it can be an option that the user opts into when they understand the implications.

**Comment by dessalines** [comment]
I'm not too keen on that, because of the privacy issues related to google speech services, but if someone else adds it, I wouldn't be opposed.

**Comment by xxxxme** [comment]
I'm against adding this to the code even if it's disabled by default just because of the potential privacy issues.
Perhaps users who like the layout but are less concerned about privacy could make a fork which implements things like voice typing, auto-suggestion, and so on, rather than adding anything like that to this app?
