### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by HollyCeuin** [dessalines/thumb-key#228]
Since this keyboard only takes up a small portion of the space in the popup, if possible it'd be amazing if we could have the rest of it be transparent. Using this on a horizontal device means I'm covering nearly half the screen when using this even though I'm only using a small section.

**Comment by dessalines** [comment]
I looked into this, and it's unfortunately dependent on the applications, not the IME services.

The actual thumbkey keyboard only takes up as much space as is shown. Even if I set the background as transparent, it only affects its box.

Applications generally use a softInputMode that pushes up their applications, so that IME services can appear below content. So the background shown on the sides, is determined by those apps, not by the keyboards themselves.
