### ISSUE TITLE
French layout

### ISSUE THREAD

**Issue by Armaldio** [dessalines/thumb-key#26]
Hello,

Would be great to have keys optimised for french typing 

Thanks

**Comment by dessalines** [comment]
I don't speak french, so someone who does would have to contribute a keyboard. I added instructions for how to do that [here](https://github.com/dessalines/thumb-key#how-do-i-add-my-language-or-layout).

**Comment by Armaldio** [comment]
Thanks a lot, i'll have a look 👍

**Comment by Kristuxson** [comment]
Hello, I tried to make the file for use in French.
I based on the corpus of [Nicolas C.](http://bepo.fr/wiki/Fr%C3%A9quence_des_caract%C3%A8res#Corpus_de_Nicolas_C.), for the frequency of letters. I also used the frequency of the [bigrams ](http://www.apprendre-en-ligne.net/crypto/stat/francais.html) to find the best location according to the most common following letters. I also added accentuated letters, character "ç", French quotes. I added brackets too as I find it convenient to have.
In CommitText actions, is it possible to add spaces before signs of double punctuations (:;?!)?


![Capture](https://user-images.githubusercontent.com/128711689/227224074-fb04814c-741d-44a2-99e3-281a888272c4.PNG)

I am new to github and I do not know how to send the file, do I have to make a pull request and how does it works?

**Comment by CastelJeremy** [comment]
Hello, i would like your feedback on this layout before creating the file.

I am using the same datas from this comment https://github.com/dessalines/thumb-key/issues/26#issuecomment-1481239292
So the letter frequency is **ESAITNRUKODCPMVQFBGHJXYZWK.**

Also i think i should add some special symbols to the layout. At least the **É**, **À** and **È**, they are really frequent in french.

![French Layout](https://user-images.githubusercontent.com/39135270/229222625-47732ddb-3c8c-415c-add2-cb2d10bf629d.png)

**Comment by dessalines** [comment]
That looks very good to me. 

Check out some of the other keyboards, especially the portuguese one, to see how they do accented vowels in a consistent way.

**Comment by CastelJeremy** [comment]
This is the layout with accented characters.
I have limited them with data from this [WikiPedia document](https://fr.wikipedia.org/wiki/Diacritiques_utilis%C3%A9s_en_fran%C3%A7ais#Combinaisons).

Does it seem usable ?

![French Layout](https://user-images.githubusercontent.com/39135270/229280707-8e380472-0a13-4ef9-9946-947da82346d5.png)

**Comment by breversa** [comment]
@CastelJeremy I volunteer to try out your layout! ;)

**Comment by breversa** [comment]
I’ve started using this french layout (I’m already a bépo user so I’m definitely not adverse to trying new layouts ! ;) ) and I find it very interesting!

Some initial feedback:
- Word prediction is needed, as thumb-typing is inherently slower than portrait/two-thumbs, or full-keyboard typing
- As a frequent emoji user, an emoji picker is a must
- on the E key, the accentuated letters could be displayed differently, more in line with the way the accents are "drawn".

For instance:
```
O Ë É
Ô E Ê
Œ   È
```
I understand you’re trying to have a consistent way to display of accents with regard with U and I, but I feel that it’s more natural this way, especially since É and È are much more frequent than Ü and Ï.

(I’ll add more comment after more testing)

**Comment by breversa** [comment]
Also, given that:
- the frequency is **ESAITNRUL ODCPMVQFBGHJXYZWK**,
- vowels on the right, consonants on the left,
- bottom first, top last,

Shouldn’t the layout be like this?
```
LRU
NIA
TSE
```
or maybe:
```
LUI
RNA
TSE
```

**Comment by breversa** [comment]
@CastelJeremy 
After experimenting a bit, I believe I *may* suggest an improvement to your french layout. :)

Here it is:
```
      ü   ï
 L   Uû  Iî
  q  pù y k

    wjg   @
 Rv zNb dAâ
    xhf   à

=^m çc! oëé
*T- :S? ôEê
/_+ ,.; œ è
```

Following your order of frequency (`ESAITNRUL ODCPMVQF BGHJXYZW K`) and these guidelines from https://github.com/dessalines/thumb-key:

- First 9 letters by frequency are the 9 center key taps. The next 8 are swipes **to** the center. The next 8 are swipes **on** the center hub key. Z is last.
- Alternate thumbs for vowels and consonants (Vowels on right side of keyboard, consonants on left). This naturally results in fast digram speeds.
- Prioritize bottom, and right side of keyboard. So EAO should be on the right side, and bottom to top, while TNS is on the left side.

I made up with this order of priority:
```
9 6 3
8 5 2
7 4 1
```

I then proceeded like this:
1. Lay out the 9 most frequent letters (`ESAITNRUL`), from bottom-to-top, right-to-left, vowels on the right
2. Lay out the next 8 most frequent letters (`odcpmvq`) and `y` as swipes **to** the center (I didn’t want to move `y` to step 3 and wanted to keep it as much to the right column as possible, although I could study moving it to the bottom-right of the center square, instead of the current `f`)
3. Lay out the next 8 most frequent letters (`fbghjxzw`) as swipes **from** the center
-- _This is where things get less and less objective_ --
4. Lay out the last letter (`k`)… where I could (it ends up in the`i` square, which is alphabetically close)
5. Keep the top and bottom position of the right square (`A`) for upper- and lower-case control
6. Lay out the accentuated letters in the same square as the non-accentuated letter, trying to keep as much consistency between `e`, `a`, `i`, `u`, `o` **and** mimicking the drawing logic (e.g. acute accent to the top-right, grave accent to the bottom-right, circumflexes and tremas as high as possible)
7. Lay out `ç` in the same square as `c`
8. Add the most common punctuation (`.,;:!?`) in the same square, trying to mimick the drawing logic (e.g. `,` and `;` at the bottom, `!` and `?` as high as possible
9. Add mathematic symbols (`+-/*=`)
10. Add extra symbols that I use frequently enough (`@^_`) that I want them on the main layout (and not in the shifted one), where they made the more sense
11. … and now I realise that I’m missing the apostrophe. I’ll get back with an updated version! ^^

**Comment by breversa** [comment]
```
      ü   ï
 L^  Uû  Iî
 _q  pù y k

    wjg   @
 Rv zNb dAâ
    xhf æ à

"’m çc! oëé
*T- :S? ôEê
/=+ ,.; œ è
```

Changes:
1. Added `’` and `"` to the bottom-left square
2. Moved `^` (same relative position as most circumflexe-accentuated letters) and `_` (at the bottom, following the drawing logic) to the top-left square

**Comment by breversa** [comment]
```
 "’   ü   ï
 L^  Uû  Iî
 _q  pù y k

    wjg   @
 Rv zNb dAâ
    xhf æ à

  m çc! oëé
*T- :S? ôEê
/=+ ,.; œ è
```
Changes:
1. Moved `’` and `"` to the L square, since "`l’`" is a frequent combination and would make for fast typing. Also, it un-clutters the bottom-left square (I know that the goal is **not** to use all the available positions! This is clearly into the "finding the trade-off between readability and completeness" situation :) )
