### ISSUE TITLE
Spaces before punctuation in French layouts

### ISSUE THREAD

**Issue by tnzw** [dessalines/thumb-key#291]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **

(I'm using 1.6.0, I'm French)
In French (fr_FR), we normally add a space before some punctuation. It matters when I click several times on the space bar.
First space appears, then comma, dot, question mark, exclamation mark, colon, and then semicolon.
Normally, for `?!:;` we use one (non-breakable) space before the punctuation,
example: `Je quitte mon emploi ; je m’apprête à en chercher un autre.`
or: `Il a dit : « Je serai bien présent. »`
or: `Quelle heure est-il ?`
or: `Quelle chance il a eue !`

For more info:
See this [link (fr)](https://www.projet-voltaire.fr/dossier-voltaire/signes-de-ponctuation-francais/).
/!\\ These rules are not the same in [fr_CA](https://vitrinelinguistique.oqlf.gouv.qc.ca/22039/la-typographie/espacement/espacement-avant-et-apres-les-signes-de-ponctuation-et-les-symboles) and maybe other fr_* languages!

** Suggestion **

I'd suggest to add "MessageEase Français (fr_FR)", "Thumb-Key Français v1 (fr_FR)" and "v2 (fr_FR)" layouts that add (non-breakable?) space before `?!:;` while cliking space several times.

…even if I think having too much layouts in the choices will make the app more difficult to use. This will be for another feature request !

Merci ! 😉

**Comment by tnzw** [comment]
I think using normal space (0x20) is the thing to do for now, as non-breakable spaces (0xA0) are handled differently between apps (or SMS encoding thingy).

**Comment by dessalines** [comment]
Feel free to add extra spaces to those punctuation markers in the french layouts, and open up PRs for them.

**Comment by tnzw** [comment]
Sorry, I won't do a PR because I don't want to spent time on it unfortunately.

However, I think closing the issue is preventing someone else to do the PR. Can we open it again please?

**Comment by dessalines** [comment]
I'll re-open it shoul someone decide to work on it.

**Comment by soupirs** [comment]
I'd wrote a `SPACEBAR_KEY_ITEM_FR` to handle spaces before ponctuation, could I add it to `CommonKeys.kt`? Or should I write it explicitely in every French layout?

**Comment by dessalines** [comment]
Probably not, because other french layouts might not want them on the spacebar key, which has a lot of custom functionality already.

**Comment by soupirs** [comment]
My intention was just to slightly modify the effect of the multi-tap on the space bar for the 4 existing French layouts. Is it a bad idea, should I add another layout instead? I think any French person would be happy with these additional spaces (but maybe not every French speaker, in fact, so yeah I don't really know).
And my previous question was more on the organization of the code: is it appropriate to add something to the file `CommonKeys.kt`, to avoid repetition in every French layout file (assuming I modify the behaviour of all of them)?

**Comment by soupirs** [comment]
I am working on that again, but modification https://github.com/dessalines/thumb-key/pull/613 annoys me. Basically I am trying to modify spacebar multitap, but when I replace `, ` with `  ?  ` instead of `? `, I get a "cursor moved" log and it ends multitap. Is there something I can do, or is it inherently irreconcilable with this "cursor moved" detection?

**Comment by dessalines** [comment]
You might need to tweak that cursor moved detector. I thought that was only supposed to fire for touch moves tho.

**Comment by soupirs** [comment]
In fact the problem only occurs in the ThumbKey test section (the detector is fired after typing every letter larger than an "i" or an "l"), it is fine everywhere else.
I am still not sure about how to make the contribution. The options I see are
1. modifying directly the spacebar key in the French layouts (which is what I do at the moment for my personal use)
2. adding a new French layout with a modified spacebar
3. I am ready to work on a keyboard configuration parameter as you suggest, but then maybe the whole spacebar multitap behaviour should be a keyboard setting instead of being parameterized inside the spacebar key? I don't see any other key than the spacebars that need a `nextTapActions` attribute.

**Comment by dessalines** [comment]
I like 1) the best, then you could add that french spacebar to all the french language layouts.
