### ISSUE TITLE
No comma on spanish keyboard

### ISSUE THREAD

**Issue by tongubin** [dessalines/thumb-key#300]
** Thumb-Key Version **
1.7.0 from f droid

**Describe the bug**
no comma on spanish v1 layout but there is an asterisk.

**To Reproduce**
1. change to spanish layout

**Comment by mockballed** [comment]
A few layouts are missing the comma:

> ThumbKeyENv4
> ThumbKeyESv1
> ThumbKeyEUv1
> ThumbKeyNLv1
> ThumbKeyNOv1
> ThumbKeySVv1
> ThumbKeyDAv2 shifted mode (also "v2" in filename but everything else is "v1").

The bottom-center key has room for it on all the layouts. I'll do a PR.

**Comment by mockballed** [comment]
It seems to be intentional: https://github.com/dessalines/thumb-key/issues/73#issuecomment-1481875247

The English Thumb-Key layout used to have a comma. The idea is to use the multi-tap function: tap spacebar twice to type the comma followed by a space, which is comparably fast to swiping.

It could be argued that you might not want to have it type that extra space or that it's good to have an alternative way to type the main symbols (_?_ and _!_ included, imo) without relying on multitap or the symbols mode.

In any case I already made the changes so I might as well submit them.

**Comment by dessalines** [comment]
I just checked, and there is a comma on the shifted keyboard, just like all the others.

Double tap spacebar for a quick comma.
