### ISSUE TITLE
Add configurable dead space between keys

### ISSUE THREAD

**Issue by Asmageddon** [dessalines/thumb-key#303]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **

Add a configurable amount of dead space between keys, to minimize the amount of mispresses.

**Comment by Asmageddon** [comment]
> Not really interested in this. The keys should be as large as possible.

If you hit the keys close enough to the borders between them, it's essentially random which one you activate. Dead space is a reasonable precaution against that.

**Comment by bklaase** [comment]
It seems to be how padding behaves currently. Came to ask whether it could NOT work like that, since I agree that keys should be as large as possible. Currently pressing/gesturing withing the padding area does nothing. But why would anyone press when no effect is desired :).

One could argue: well, simply don't use padding. But I really like the aesthetic of it!
