### ISSUE TITLE
Swap space and backspace in split layout

### ISSUE THREAD

**Issue by SeerLite** [dessalines/thumb-key#307]
- [X ] Did you check to see if this issue already exists?
- [X ] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [X ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

** Describe the feature request below **
I find the current split layout very unintuitive with the backspace in the place where usually the spacebar goes. I'd like to have an option to swap them.

**Comment by dominmana** [comment]
@SeerLite if you look at #292 there's the following explanation by @mockballed 

> This layout introduces a fourth column for letters and switches to a vertical, centered spacebar.

> The idea is that each thumb gets assigned to a couple of columns and that they can reach horizontally to alternate pressing the spacebar. It also works well with one handed typing.

> Design points

> The spacebar is the most used key by far. Trying to reduce thumb fatigue by having it through the middle of the keyboard to avoid reaching down to tap it.

> Backspace positioned at the usual place of the spacebar and shift/caps-lock are set as vertical swipes there.

**Comment by SeerLite** [comment]
Thank you, that explains why the decision was made.

**Comment by mockballed** [comment]
Yeah, the placement is unusual. It took me some time to get used to it.

The spacebar is pressed twice as much as the next most common key (the letter _e_). On a physical keyboard, it is readily accessible by the thumbs that rest on it.

I'm trying to find a good analogue for a touch-screen so that the spacebar would be "right there" at all times.

I'd like to try some gesture-based way to produce a space, like pressing both thumbs at the same time anywhere on the keyboard.

A 2 wide tile spacebar might help (the backspace could be shorter to allow for other buttons).
![split_wide_spacebar](https://github.com/dessalines/thumb-key/assets/8158663/bc5921a6-b4c0-4eaf-83d8-db5f185483ed)

**Comment by SeerLite** [comment]
@dessalines Why not? All regular Thumb-Key layouts do have the spacebar in the bottom.
Would you accept a PR with a clone of the split layouts with the spacebar moved?

**Comment by dessalines** [comment]
Sure, feel free to open up PRs with the new layouts.

**Comment by alensiljak** [comment]
@SeerLite, did you ever submit the modified layouts? I have exactly the same remark as you.
