### ISSUE TITLE
Theme Support

### ISSUE THREAD

**Issue by 0xFOSSMan** [dessalines/thumb-key#367]
- [yes] Did you check to see if this issue already exists?
- [yes] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [no] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
More themes or (if possible) a more comprehensive theme support via .zip files or such.
Missing Dracula here :smile:

**Comment by WadeWT** [comment]
Hello, I made a post about this on [Lemmy](https://lemmy.sdf.org/post/2562624) and just wanted to include my images here as theme examples. 
![ThumbKey UI_1](https://github.com/dessalines/thumb-key/assets/7088087/602db379-c1c0-4277-b3a9-d263bd7f03c1)
![ThumbKey UI_2](https://github.com/dessalines/thumb-key/assets/7088087/0e5cc85c-ecb6-4e19-a802-19ac3e9abe8a)

**Comment by dessalines** [comment]
[This file holds the themes](https://github.com/dessalines/thumb-key/blob/main/app/src/main/java/com/dessalines/thumbkey/ui/theme/Color.kt), you can use [this tool](https://m3.material.io/theme-builder) to generate any ones you like.

I'll close this issue, because we already support themes, and I'd be happy to add any ones that ppl make PRs for.

**Comment by WadeWT** [comment]
> 

It doesn't look like this addresses different button shapes, would that be better put as a separate feature request?

**Comment by dessalines** [comment]
Yep, that could either be different feature requests, or PRs.
