### ISSUE TITLE
Language selector

### ISSUE THREAD

**Issue by Vander567321** [dessalines/thumb-key#396]
The app might never get translated into any possible language. Its very common to provide an option to choose an existing translation instead forcing system language or english.

**Comment by dessalines** [comment]
This is just to be able to see the settings pages in a non-system language? I don't think that's anything I want to support, and I don't know any other apps that do this.

**Comment by alerque** [comment]
Quite a few other apps do actually. I believe the logic is that the system may be the user's actual preferred language, but that language may be obscure and many smaller apps don't actually get translated to their preferred language. The user's fallback preference may be German or something common rather than English. Lets say they speak Kazakh but also know Russian (a common scenario). Android has Kazakh, but some specific app might not. Instead of falling back from Kazakh to English they would prefer to fall back to Russian. Setting a preference for the app from languages that are actually an option for the app is sometimes useful for this scenario.

That being said I kind of agree it might not be worthwhile for a keyboard app. More practically just get translation strings for the languages people actually want and that match their system ;-)
