### ISSUE TITLE
issue with type-split english v2: Missing Emoji and Caps Lock

### ISSUE THREAD

**Issue by Docbroke** [dessalines/thumb-key#432]
**Thumb-Key Version**
2.0 and 2.1 from f-droid

**Describe the bug**
Unable to change keyboard layout. Globe symbol near # key for changing keyboard layout has disappeared after version 2.0

**Comment by racuna** [comment]
The same is happening with Spanish and Portuguese TypeSplit, maybe other TypeSplit layouts as well.

**Comment by sslater11** [comment]
Ah yes, this is my fault. I changed the swipes on the number switch key, to allow for better controls on the non-type-split keyboards. I also did this because I added an emoji key and moved the layout switcher from the number key to the emoji key.
![newswipes](https://github.com/dessalines/thumb-key/assets/43177940/8985ee91-ee12-401c-9380-899860fa7853)

This bug is on every type-split layout, and the wide-english layout.

I've been wanting to chat with those who use the type-split layouts, so that I can ask how we can add this emoji key to the layout.

We could possibly change one of the space bar buttons to the emoji key, or we can add a swipe to one of the spacebar buttons to get into the emoji picker, and add swipes for the Settings, Layout switcher, Keyboard move, and Keyboard switcher.

Something to also keep in mind is that we have a new feature called 'slide gestures'(see it in settings), and this doesn't work on the type-split layouts. Slide gestures allows us to move the text cursor by swiping left and right on the spacebar. It also allows us to select text using the spacebar, and we can swipe on the backspace key to select and delete text.
Please see this demo of it in action
![swipe-gestures](https://github.com/dessalines/thumb-key/assets/43177940/b8f656be-69d6-4973-9c95-1b603f2f43a4)

The slide gestures feature doesn't work on type-split layouts, there's two solutions. I can write the code to make it work, or we can move the spacebar to the bottom of the screen, replacing the backspace key. If we move the spacebar to the bottom of the screen, this frees up the 3 middle buttons. The second option is easiest for me to implement, but it's really up to what you guys n gals want.
We can have space bars with swipe actions(settings, layout switch, etc) and the swipe gestures too, the swipe gestures can be enabled after you swipe further than 1 key away from the center of the main space bar.

**Comment by Docbroke** [comment]
1. I feel that we should move space-bar down replacing backspace key. This will make it more in line with other layouts. Personally I am not comfortable using space-bar in the middle.
2.  We can move period and comma (. and ,) as swipes with N key. Period (.) as down swipe and comma (,) as right swipe. 
3. We can also add hyphen (-) and quotation (') as left and up swipe to N key, if desired, I don't mind if this keys are kept for numbers key layout.
4. This shall free up all 3 keys, which can be kept similar to standard 9x9 thumb key layout.
5. I am not sure what to do with left corner key, it can be kept empty or used for something else.

**Comment by XJ-9Olev** [comment]
I like the Type-Split layout as is. The middle space bar buttons feels significantly better to me then having to reach down for space. Additionally, I would not like for any of the keys which are mapped to swipes on the middle row to be removed. Having the apostrophe on the base layer is second only to the middle space for me in terms of utility.

Now, the emoji key could take the place of the topmost space key in the number layer potentially. Since there is already a way to access the settings on the base layer, I've always felt that having it in the number layer as well is redundant. Additionally, I find that I personally hardly ever use the topmost space key.

As for the slide gestures, although it would be nice to have that feature, as I do think it is a neat QoL improvement, I'm having trouble imagining how it might work unless code was cooked up to allow it to work on Type-Split's single space keys. One solution I can imagine is having the slide gestures work on the backspace button and in turn giving it the ability to delete multiple characters when held down; users could toggle which functionality they want on the backspace key when they swipe. This is of course asking too much, though, making it an extremely inefficient suggestion.

**Comment by sslater11** [comment]
Please keep in mind that any changes will also affect all the other typesplit language layouts :smile:.

I'm happy for any changes to be made, and think this could be a lengthy discussion on what should go where.
I'd like to keep the swipes on the number key the same, because that's the same in every thumbkey layout. If however you want a different layout for it, it can be implemented. Realistically I'd like the emoji key and number key that's on other layouts to be included in this, but it's just where to put them! We could shrink the size of the backspace key, allowing the emoji key to go next to the number key. That seems like an easy solution, although they layout would look uneven.

@XJ-9Olev The swipe feature you mentioned for backspace already exists, please watch the GIF I on my post above. You swipe backspace to select text, and release to delete. You will be able to move the cursor by swiping the spacebar in the middle of your keyboard, because once you swipe your thumb about 1 key length away from it, it will activate the cursor moving. To then trigger the selection mode, you just move your thumb upwards.

**Comment by WadeWT** [comment]
I like the idea of making the top space bar the emoji key, I never use that space bar anyway, though I only speak for the English layout, not sure if that key has any useful characters for other languages.  If the top space key is impractical  I'm cool with having it to the left of the enter key.  The layout being asymmetric isn't a big issue, not over usability anyway.   I think it would also be nice if the existing small space bars could be made to work with the new swipe selections.

**Comment by XJ-9Olev** [comment]
@sslater11 Oh, I apologize for overlooking your demo. I assumed for some reason that because it was on a different keyboard, it wouldn't apply to Type-Split proper. I've watched the whole thing now, and I see that you not only implemented what I was thinking of, you did so in a much more featureful way.

I think I do like your implementation of deleting text in the demo. Although it adds an extra step if one just wants to delete the previous word, it's that extra step that allows for conveniently deleting more text when needed. I'd very much be up for trying out that functionality.

Regarding other languages, I use the German and Italian keyboards sometimes, and all the Type-Splits use the same number layer. That means the topmost space key in it could be safely replaced with the emoji key.

**Comment by sslater11** [comment]
**An update:**
I have been on holiday and then at work a lot, but I've managed to get the slide gestures working along with keeping normal swipes on the space key(the backspace key already worked properly). What I mean by this is we can swipe left right on the spacebar to move the cursor by a single character, or we can swipe sideways even further to move the cursor as shown in the demo above.

I think the easiest solution for adding the emoji key would be to put it in the place of the top spacebar key.
All type-split layouts have the same spacebar buttons, so I will move the * character on the top one to the bottom left corner of the bottom key, because this is the same place where the * character is in the numeric mode.


![typesplit with emoji](https://github.com/dessalines/thumb-key/assets/43177940/9b84d6f9-87c0-4e2c-b3fe-cc9597315739)

What's everyone's thoughts/feelings about this? :smile:

**Comment by XJ-9Olev** [comment]
Look great. I can't wait to see this implemented.

**Comment by mockballed** [comment]
Good stuff, sslater11. I don't use the top spacebar as well.

I like the back and forth about the spacebar's position. typesplit was [designed](https://github.com/dessalines/thumb-key/issues/307#issuecomment-1629349977) around its vertical spacebar, but ideally the spacebar's placement should be user-configurable (a PR for another time).
