### ISSUE TITLE
Categories of layouts

### ISSUE THREAD

**Issue by DobriniaMerk** [dessalines/thumb-key#447]
**Describe the feature request below**
It would be convenient to have layouts in settings organized in folders by language or type, because scrolling through all of them is too long.

**Comment by dessalines** [comment]
I'd rather not do this, because a lot of keyboards aren't going to fit into categories, and this could get extremely complicated really quickly.

Examples:

- A multilingual keyboard that maybe 1-2 ppl use, with 3 different languages supported.
- A special programming keyboard with some specific characters that are different from other "symbol"-type layouts.

Plus it would require a bunch of changes to alorma/compose-settings that I don't have time to do.
