### ISSUE TITLE
new futureproof system for sorting layouts

### ISSUE THREAD

**Issue by Ingegneus** [dessalines/thumb-key#467]
- [x ] Did you check to see if this issue already exists?
- [ x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
i've seen a FR where someone wanted folders in which the layouts would be organized and that is obviously difficult with multiple languages for the layouts. I propose using a tag system, where you could insert the tags (eg languages, split...) and get the appropriate layouts. also within this system have a short description of what the aim of that layout is. for example there might be an english layout with a few tweaks that are intended for a specific purpose, which makes it hard to figure out the differences and pros cons of that layout over another english layout

**Comment by WadeWT** [comment]
I think a tag system would be nice, too, at the moment the one long list works fine considering you only really need to go through it once or twice to find your preferred layout, but if keyboards keep getting added it'll get a bit overwhelming.

**Comment by dessalines** [comment]
Just remember not to start categorizing / doing any work on this unless the solution works with the alorma compose-settings multi-select.

**Comment by KraXen72** [comment]
i think this would be great!

**Comment by KraXen72** [comment]
it would be especially useful for differentiating which layouts are derived from others (like the EN+SK) vs. original ones that respect letter frequency. since if somebody is searching for a layout, and only one that exists is one that's derived from english, it might not be easy to find by name alone

**Comment by racuna** [comment]
Maybe thinking about it a bit more in the long term, because of the "future proof". It would be interesting a way to customize each keyboard layout adding additional parameters besides the language, like Type (Thumbkey, messagease typesplit, wide), Theme Color and Dictionaries (this last one is not implemented yet, but could be in the future).


For example, for someone bilingual:

- PT, TypeSplit, Green, Brazilian Portuguese dictionary and "next word prediction".
- EN, Messagease, Blue, American English dictionary and "next word prediction".

The possibility to choose colors for each Layout might seem irrelevant, but it could help a lot as a visual reference when switching between languages constantly.

**Comment by dessalines** [comment]
Can re-open if someone wants to work on this, but our settings's library's multi-select doesn't support tagging or filtering.

**Comment by Theblackcat98** [comment]
> Can re-open if someone wants to work on this, but our settings's library's multi-select doesn't support tagging or filtering.

I looked at the library that you use and I think there is an easier approach to this. The easiest and most organized method would be to use the `triState-checkbox` that is available in alorma/settings-compose library.

<img width="452" alt="triState-checkbox" src="https://github.com/dessalines/thumb-key/assets/4934499/c360ef4a-7ae0-4535-a42a-6fed54b21034">

As the main **issue** that I see mentioned is the visual clutter of a long list, we can use the `triState-checkbox` to *nest* layouts under each language.

---

As an example:
```
English
    | __ Compose-Thumbkey
    | __ Messagease
    | __ Thumbkey v2
    | __ Qwertiese
Spanish
    |__ etc.
```

**Comment by KraXen72** [comment]
this would make the UX somewhat *interesting*
