### ISSUE TITLE
Floating mode

### ISSUE THREAD

**Issue by AeliusSaionji** [dessalines/thumb-key#470]
It would be very convenient if thumb key could be a floating keyboard, so that it may be resized and moved all over the screen.

I want this in part because my phone is rather large and I want to have the keyboard very high up in portrait mode, But without obscuring half of the usable screen.
Also, This is more Android's fault, but Android on phone is functionally unusable in landscape mode without a floating keyboard. This is exacerbated by my phone's 21:9 aspect ratio.

Thanks!

**Comment by dessalines** [comment]
I don't see myself adding this, but I spose if someone else wanted to work on it, I wouldn't be opposed.

**Comment by alerque** [comment]
I've never used a floating keyboard (didn't know that could be a thing on Android) but I could see this being *very* useful. I would use it especially on my e-ink Android tablet.

A related question: I'd never thought about it but thumb-key or other square-aspect keyboard would work great on a landscape oriented phone if the panel could come it from the side instead of the bottom. As noted landscape mode is virtually useless right now. Is such a thing possible (not floating, just a split panel but from a side)?

**Comment by dessalines** [comment]
I use this in landscape mode pretty consistently, it just pushes up a lot. No there's no "side-push" in android.

**Comment by dessalines** [comment]
Will re-open should someone want to work on this.
