### ISSUE TITLE
Space bar swipe up, swipe down is up arrow, down arrrow.

### ISSUE THREAD

**Issue by 4-3is4-me** [dessalines/thumb-key#480]
I am a termux user, access to the command history with up arrow/corsor up and down arrow/cursor down, or for use in a text editor is desirable. It seems intuitive for this to be incuded with the left and right swipes of the space.

**Comment by dessalines** [comment]
You can add these to the english programmer layout, seems like the best place for them.

**Comment by sslater11** [comment]
I've already implemented this in PR #439

**Comment by storvik** [comment]
@dessalines this can be closed 🎉

**Comment by sslater11** [comment]
Actually, not neccessarily. As KraXen72 said in my recent pr, the spacebar up and down swipes were taken out of ThumbKey before, because a user kept accidentally swiping up and down, moving the cursor whilst they were typing.

I'm thinking we could add a setting to enable/disable the up/down swipes on the spacebar.

I have also accidentally swiped up whilst using the spacebar, causing my typing to be affected, so I don't know if I want it on or not lmao.

**Comment by dessalines** [comment]
Seems like most ppl including me don't want this.
