### ISSUE TITLE
Standard Japanese layout

### ISSUE THREAD

**Issue by elizagamedev** [dessalines/thumb-key#536]
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [x] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**
The included Japanese kana layouts are arranged completely differently than the typical layout on mobile phones, like the below image.

![](https://files.tofugu.com/articles/japanese/2016-04-18-how-to-install-japanese-keyboard/android-typing-ku.jpg)

It would be nice to have this layout available in thumb-key as well. I'm also wondering if the extant layout was popularized elsewhere and i just havent encountered it yet.

(maybe i'll submit a PR if it turns out to be trivial)

**Comment by K0baU** [comment]
I designed the layout. I tried to follow the guideline in the readme and sorted the characters according to how frequently they are used. However, Japanese are very used to use swipe input method shown in your image. Since I agree that being user-friendly is more important than following the guideline literally, I admit designing the layout myself was not a good idea. I don't mind turning the layout into the same one as you show. No one will mind it because I am probably the only one using my layout. Well, I don't really prefer my layout to common one.

**Comment by K0baU** [comment]
By the way, just making the layout same as the common one is  not enough to make it as useful as common keyboard. Natural Japanese requires kanji, known as chinese characters, to type complete sentences. Now I am planning to design kanji keyboard, but it will take me a lot of work, since Japanese regular-use kanji includes as many as 2136 characters. (According to Wikipedia, Chinese use even more characters.)

**Comment by elizagamedev** [comment]
Thank you for responding. It would be nice to have kanji input in thumb key someday, but for quick kana input without having to switch keyboards would be useful. I'll submit a PR to change the layout when I can.

I'm working on another project called [Libre Japanese Input](https://github.com/elizagamedev/android-libre-japanese-input) which will restore the old open source Google Japanese Input app to Android. If thumb-key ever supports completion candidates, I'd also like to add built-in mozc support for thumb-key as well.

**Comment by dessalines** [comment]
Will re-open should someone want to add a Japanese layout.
