### ISSUE TITLE
On landscape mode, display both numbers and letters pane

### ISSUE THREAD

**Issue by Evengard** [dessalines/thumb-key#642]
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**

In landscape mode the space is underutilized. Is it possible to show both letters and numbers at the same time in landscape (similar to messagease)?

**Comment by nightkr** [comment]
This would be great to have on larger portrait displays too.

**Comment by nevans** [comment]
For example, this is how my MessagEase currently looks:

![Screenshot_20240204-102851.png](https://github.com/dessalines/thumb-key/assets/6142/879aea58-92b2-417e-8a0b-0fe3a26e1314)

Additionally, I believe MessagEase-style config for this is more appropriate.  That is, rather than requiring an entirely new layout, it is simply a config option for all existing layouts.  See their settings for this:

![Screenshot_20240204-102752.png](https://github.com/dessalines/thumb-key/assets/6142/4c1ed394-a817-4ea1-84bd-c805ce949d4f)

![Screenshot_20240204-102831.png](https://github.com/dessalines/thumb-key/assets/6142/c23e22a1-5179-4c6c-9bb3-fcd7b27c76b3)

(I can create a separate issue for the config style.)

**Comment by nevans** [comment]
This issue _could_ be solved by simply adding another layout... so my comment felt like scope creep and I created another issue:
* #655

But (as mentioned in that issue) if the "add another layer" approach is extended to other language layouts (not to mention alternative number pad layouts) it would lead to a combinatorial explosion of layouts.

**Comment by dessalines** [comment]
Yep, the correct way is to add another layout for wide screens that has letters and numbers wherever you like.

**Comment by dessalines** [comment]
Due of #655
