### ISSUE TITLE
Add composition as a toggle option in all layouts

### ISSUE THREAD

**Issue by quasipedia** [dessalines/thumb-key#663]
As a user with a complex identity who types primarily in a language with a given set of accented letters, and secondarily in a language with a different second set of accented letters, I would like to be able to choose if the keyboard should try to compose characters independently by what layout I chose (=it should be a separate checkbox under the layouts option in the settings). Unwanted (accidental) composition should be undone with a backspace

Example:
 `a` followed by `"` will result in `ä`.  If the user now taps `backspace` it will result in `a"`.

This is useful because you may for example primarily type in Swedish and have the letters `äëöå` as primary taps/swipes, but you may occasionally text to an Italian relative, and want to be able to quickly compose `àèìòùáéíóú`, rather than switching the full layout, where the position of the main taps/swipes change.

Other than that: this project is amazing.  I have been using MessagEase since my palm III time (yes! MessageEase pre-dates smart phones!) and finding a free and open source version of it has been a godsend! <3

**Comment by dessalines** [comment]
This would be something better on a per-key basis. Not all letters have composed types. 

@quasipedia could you handle this one?

**Comment by smurfix** [comment]
IMHO you can ignore whether letters have composable types or not. You just need a way to enter the combining diacritical of your choice. In principle, assigning keys to them should be sufficient.

For displaying the diacritical on the keyboard you probably need to emit either a punctuation space U+2008 or a ◌ U+25CC (the latter would make distinguishing between an accent and a cedilla easier …) in front of the diacritical mark.

Backspacing through a letter+plus+diacritical sequence should separate the two by inserting a punctuation space, then another backspace should remove both the space and the diacritical.

**Comment by dessalines** [comment]
@smurfix can you handle this one?

**Comment by smurfix** [comment]
I'm not exactly out of work, but I'll have a look at the code.

**Comment by smurfix** [comment]
Well, this seems tractable. First (and rather easy) step: remove the explicit compose tables and simply append u0301 instead of replacing an a with an á. Same for the others. You might want to replace the ç cedilla special-case with Compose+Comma u0327, that way users can write a z̧ or even an ẍ̧̀ if they need that.

Oh yes, special case: if the last character is a space: replace it with the non-combining version of the mark. Combiners are not displayed on spaces. (Alternately you could replace the space with its non-breaking sibling u00A0.)

What currently is not tractable, however, is my work system's inability to run Gradle. 🤬 The stupid errors I get are beyond my ability to track down, let alone fix, given limited free (or even "free") time. Thus I'm sorry but as much as I'd want to I can't provide you with a pull request that has a non-zero chance of actually compiling, let alone working.
