### ISSUE TITLE
Please add a "hide keyboard" feature

### ISSUE THREAD

**Issue by Sciencealone** [dessalines/thumb-key#668]
- [+] Did you check to see if this issue already exists?
- [+] Is this only a single feature request? Do not put multiple feature requests in one issue.
- [-] Is this a question or discussion? Don't use this, use https://lemmy.ml/c/thumbkey

**Describe the feature request below**

Thank you for a great alternative to MessageEase!

I would like to suggest a useful feature I am missing. Currently, I cannot hide a keyboard once opened, so need to reopen the page/screen to get a wide view.

MessageEase has this option on a button currently dedicated to emoji toggle on Thumb-key. Can we make this emoji feature optional/customizable? I believe the hide operation will be preferable for many users.

**Comment by dessalines** [comment]
The back button on your device hides the keyboard.

**Comment by Sciencealone** [comment]
Thank you for the clarification.

> The back button on your device hides the keyboard.

But it is not convenient in full-screen apps. Would it be possible to add this feature later?

**Comment by dessalines** [comment]
I can't really speak to this since every android device I've used for the past several years uses full screen gestures, where a back button is always available by swiping from the side of the screen.

This seems like such a rare use-case (using a keyboard while disabling android gestures and / or hiding buttons) that I don't think its worth adding.

**Comment by bcm314** [comment]
> I can't really speak to this since every android device I've used for the past several years uses full screen gestures, where a back button is always available by swiping from the side of the screen.

I know about this feature only since I owned my last tablet (maybe 1 year ago) and it's not a standard android behavior. On this tablet it's the own implementation of the GUI by the company HONOR. I haven't this feature on any of my other devices.

> This seems like such a rare use-case (using a keyboard while disabling android gestures and / or hiding buttons) that I don't think its worth adding.

So I'm also one of the "rare users".  :-(

I would appreciate such a feature, because it's more comfortable, but of course I also accept your oppinion. Still wondering, that it's an hardware related thing to implement and not somthing like close/hide current app.

**Comment by dessalines** [comment]
For such a weird case, I'd recommend adding full screen gestures to your device, something like FNG.
