### ISSUE TITLE
Feature Request: Import local .kt files

### ISSUE THREAD

**Issue by allaboutevesn1987a** [dessalines/thumb-key#75]
Having an option to import a local .kt might address some of the punctuation requests that keep popping up and allow tinkerers to create layouts as suggested in the readme but without the need to trouble the devs for every "add / and ° because I use it all the time" type request.

**Comment by dessalines** [comment]
That wouldn't be doable, because these are loaded at compile-time. 

Also, its no problem to merge punctuation requests or other slight changes... I prefer that because it ensures that updates / additions are available to everyone, and people can collaboratively give feedback on the current keyboards.
