### ISSUE TITLE
UX issue | Undo easily triggered accidentally

### ISSUE THREAD

**Issue by josephmanghan** [dessalines/thumb-key#988]
### Language

English

### Variant

English symbols messeagease

### Kind of request

Changes on an existing layout

### More details

On layout "english symbols messagease" (and I presume others), the undo button/arrow is extremely easy to hit and accidentally remove a large portion of text. If typing quickly & you type a few characters after this happens, you won't be able to put the delete text back with the redo button/arrow. This is largely an issue when accessing characters around the "r" key. 

An MVP solution could be to make the the undo/redo buttons configurable in the "look and feel" menu. It would also be great if undo/redo simply wasn't available in the letters pane, and only in the special characters pane, as at least this would be more deliberate. 

![Screenshot_20240725-072635~2](https://github.com/user-attachments/assets/96707ae4-d8a5-4047-a5b2-02f8991ea819)

### Acknowledgements

- [X] I have written a short but informative title.
- [X] I have searched the existing layouts and issues to confirm that this  layout either does not exist or was not requested already
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements. 🤡
- [X] I have filled out all of the requested information in this form.

**Comment by dessalines** [comment]
> On layout "english symbols messagease" (and I presume others), the undo button/arrow is extremely easy to hit and accidentally remove a large portion of text. If typing quickly & you type a few characters after this happens, you won't be able to put the delete text back with the redo button/arrow.

I was able to replicate this, but I don't know if its *that common* an occurence that we need to add a setting just to hide those. Backspace seems like it would be just as common to swipe, and if we had no undos keys at all, there's be no way to bring back that text either.

I wouldn't oppose a PR adding this setting (default off), but to me it just seems overkill.

**Comment by josephmanghan** [comment]
It's perhaps more of an issue in left hand mode, which I use.

**Comment by locrianz** [comment]
This happens to me extremely often and I'm right-handed.

**Comment by Nixill** [comment]
I sometimes struggle with fine motor control, such as exact positions of my fingers on a touch screen. If I put my finger a little too far to the right when trying to type an L, I lose up to *an entire conment box* worth of text (however much I've typed since the last time I had to backspace), and if I'm in the middle of typing at about 50 wpm then I won't notice what I've done before I've already cleared the undo history by typing the next letter.

If you don't want to lose the undo feature (which tbh I don't either, I just don't want it to be so easy to unintentionally invoke), it could be assigned to either of the empty swipes on that button. Even making it down-left instead of left would be a big improvement.

**Comment by josephmanghan** [comment]
Very much agreed with this & a down-swipe may be a great alternative
because it's more distinct from the use of the 'r' key.

I think the undo is doubly problematic because the redo memory is so short.
I can never redo my accidental deletion.

**Comment by Noitarud** [comment]
I may accidently trigger undo when entering an L(same button position as seen in image, but is left sweep) probably because finger landed too far right; and the guesture for redo fails possibly bc too close to right side, get num/lett switch.

(perhaps abstractly related: noted the ")" is difficult to enter, only possible if I swipe from left side instead of centre.)

contemplate these solutions:
•sweep on space for undo/redo
•Add small gap to move from edge of screen

excellent app (there are some features I miss from anysoft, had to change though)

**Comment by nejni-marji** [comment]
when i get the compilation working again i might just move undo/redo onto the delete button in personal builds

**Comment by Noitarud** [comment]
if you were replying to me, undo is fine, I cannot redo due to proximity to right side (backsp is near right also)

**Comment by nejni-marji** [comment]
i would move undo/redo to be vertical on the backspace key because of how easy it is to accidentally input undo and then delete (which as mentioned, prevents redo)

**Comment by dessalines** [comment]
I'd like to leave the backspace swipes alone (partly because the left and right ones are already taken).

How about moving them to the bottom left and bottom right of the number key. Would that solve the issue?

**Comment by Nixill** [comment]
I wasn't very clear in my original comment, but that was in fact my suggestion - so I think it would likely work fine.

**Comment by nejni-marji** [comment]
i think if undo is on the left of a right-hand panel it's gonna get used accidentally

**Comment by dessalines** [comment]
What isn't going to get used accidentally? Why isn't this happening for all the other ones on the left side?

**Comment by Nixill** [comment]
Well, in most cases, an accidental misinput is just a couple backspaces away from being fixed, even if you've typed another character or two since. If you're typing fast enough that you don't react to an undo before you've made another input, there's no way to fix that besides to retype what was deleted.

**Comment by josephmanghan** [comment]
Yeh I agree, the main issue is that the undo button stores just one action.

**Comment by dessalines** [comment]
I'm not going to build an entire undo manager into thumb-key, so yall better decide where these should go so that you're not going to have this problem again.

**Comment by Nixill** [comment]
I'm okay with diag-south swipes, or it could be south and southeast in some order.

**Comment by dessalines** [comment]
That works for me 👍
